### ISSUE TITLE
Create #growth infrastructure 

### ISSUE THREAD

**Issue by cbeams** [bisq-network/dao#16]
- [x] Create Slack channel (#growthhacking)
 - [x] Create GitHub repository
 - [x] Set up notifications from GitHub repo => Slack channel
 - [x] Register repo in  .mrconfig
 - [x] Link repo to #dao ZenHub board
 - [x] Create bisq-network/roles issue as appropriate
 - [x] Create GitHub team as neccessary
 - [x] Grant GH team admin rights to repo

/cc @ripcurlx

**Comment by ripcurlx** [comment]
@cbeams Could you please grant me writing permission to the growth repository?

**Comment by cbeams** [comment]
Done, @ripcurlx, thanks. Sorry I missed that yesterday when setting up the repo.

**Comment by cbeams** [comment]
Closing as complete.
