### ISSUE TITLE
Create Bisq DAO Google calendar

### ISSUE THREAD

**Issue by cbeams** [bisq-network/dao#17]
Useful for tracking compensation request / voting windows, upcoming Zoom calls with the community, etc.

 - [x] @ripcurlx to create the calendar

Also:

 - [x] @ripcurlx to hook the calendar up to a Slack channel, probably #dao would be fine. I don't think we need a separate channel for this. #general might be even better though, to ensure the maximum number of people see new calendar notifications. It will probably never be high-traffic anyway.

 - [x] TBD to Embed the calendar the bisq.network/community page or somewhere similar

@ripcurlx, please make sure that I (@cbeams) have access to edit the calendar, so I can manage it with regard to voting windows etc.

Anyone who chooses to can subscribe to the calendar, but we assume only those working under the Bisq DAO in a fairly dedicated way will want to do that. For everyone else, it'll just be a convenient way to get an overview of upcoming events, etc.

 - [x] @cbeams to add upcoming conferences to the calendar as well, e.g. 34C3 in December.

**Comment by ripcurlx** [comment]
- [x] calendar created [1] 
[1] https://calendar.google.com/calendar/embed?src=adfiuiokq9jtac8t9keomc00b0%40group.calendar.google.com&ctz=Europe%2FVienna
- [x] slack integration to #general done
- [x] access permission to @cbeams granted

**Comment by cbeams** [comment]
Closing as complete. The new calendar can be found and subscribed to at https://bisq.network/calendar.
