### ISSUE TITLE
Register past contributors for BSQ token genesis distribution

### ISSUE THREAD

**Issue by cbeams** [bisq-network/dao#2]
- [x] Create application Google Form (https://goo.gl/forms/QM3lWU5VGjyz7RzK2)
 - [x] Tweet a link to the form (https://twitter.com/bitsquare_/status/888386074300604416)
 - [x] Send out a newsletter with link to form (bitsquare/newsletter#2)
 - [x] Reach out specifically to `brew cask` maintainers
 - [x] Reach out specifically to those listed in https://github.com/bitsquare/bitsquare/graphs/contributors

**Comment by cbeams** [comment]
## Status update

We're currently at 105 registered past contributors. We'd like to see 150 at least. Newsletter will go out later today, let's see what that does.

**Comment by ManfredKarrer** [comment]
Added list of all contributors + all users active in issues:
https://docs.google.com/document/d/1bz1nQ8EaTuS8t1sRcAuVDmXfZ451xd0zjKusHfh67KM/edit

1446 entries!

**Comment by cbeams** [comment]
Closing as complete. As the July 31st application deadline has now passed, the application form has been disabled and links to it removed from the website.
