### ISSUE TITLE
Invite Bisq / Bitsquare contributors to apply for BSQ genesis distribution

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/dao#4]
@gubatron, @undso, @wodry, @yousefamar, @SMH17, @sponnet, @datsiuk, @layer1gfx, @bitsgh, @btcll, @ligi, @arichnad, @troggy, @Z819, @ysangkok, @JoshLambda, @amuelli, @msgilligan

Each of you have contributed to Bisq (formerly Bitsquare):

 - https://github.com/bitsquare/bitsquare/graphs/contributors

There are more contributors but those are mostly already contacted by other channels.

If you're not already aware, the Bisq team is getting ready to launch the [Bisq DAO](https://bisq.io/dao), and along with the new BSQ token.

At launch time, we'll be distributing BSQ tokens to past contributors like yourselves. We appreciate a lot that you took time for supporting the project and this is our way of saying thanks!

To be a part of the BSQ distribution, you just need to fill out the application form at https://goo.gl/forms/QM3lWU5VGjyz7RzK2, and we'll be in touch with you as the launch date approaches.

Feel free to ask any questions here, or [chat with us in Slack](https://bisq-slack.herokuapp.com). In any case, I'll leave this issue open for a few days before closing it out.

Note that the deadline for applications is July 31st. Thanks again!

**Comment by cbeams** [comment]
Closing as complete. Thanks all who applied!
