### ISSUE TITLE
Update to latest Java 8 JDK to enable unlimited cryptographic policy

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/dao#43]
With 1.8.0_152 the unlimited cryptographic policy can be enabled by the security property.
http://www.oracle.com/technetwork/java/javase/8u152-relnotes-3850503.html

We should require to latest Java 8 version (1.8.0_162) and add the setting of the security property for the next build.

**Comment by cbeams** [comment]
Got it, thanks. Will take care.
