### ISSUE TITLE
Rebase October stake changes

### ISSUE THREAD

**Issue by cbeams** [bisq-network/dao#9]
Now that October voting is complete, we need to rebase stake back to 2.5 MM in a new distribution. It should be possible to do this using the existing set of testnet addresses and testnet coins, in a "re-distribution" transaction. Note that, per the spreadsheet, there was one new BSQ address added that does not yet have a testnet address assigned to it.

**Comment by ManfredKarrer** [comment]
Not 100% sure what you mean with re-distribution tx. 
My plan was to use all existing bsq utxos as input for the new genesis and add the amount of mining fee needed.

**Comment by cbeams** [comment]
That is in fact what I mean.

**Comment by ManfredKarrer** [comment]
Done: https://testnet.smartbit.com.au/tx/f8b65c65624bd822f92480c39959f8ae4a6f94a9841c1625464ec6353cfba1d9

There was 14 BSQ less due rounding issues. I added 1 BSQ to the last 14 addresses.

**Comment by ManfredKarrer** [comment]
Seednode updated with new version and tested with a Bisq testnet app. Code committed at https://github.com/bisq-network/exchange/commit/7067b0f3be00cabe57d6e6f93f9358356917dd92

**Comment by cbeams** [comment]
Great, thanks @ManfredKarrer! I'm reopening this to make sure that we follow up with two things:

 - [x] @cbeams to get the BSQ stake and voting spreadsheet ready for November with new balances.
 - [x] @grazcoin to update grazcoin/bisq-explorer to point to the new genesis tx (see grazcoin/bisq-explorer#1)

**Comment by ManfredKarrer** [comment]
@cbeams Ah forgot the explorer. I will update the jar file there but I think @grazcoin has to do something on the server as well

**Comment by ManfredKarrer** [comment]
I updated the jar and restarted it. 
@grazcoin: Can you document somewhere what need to be done on the http server side?

**Comment by cbeams** [comment]
Closing as complete. Per the commit above, I've now updated the textfiles in the cbeams/ledger repository to reflect the rebased BSQ stake after October voting, and I've also updated the 2017.11 BSQ stake and vote tracking spreadsheet to reflect the new numbers. Please see the commit comment for further details.

Also, I see that after @ManfredKarrer updated and restarted the explorer, that both genesis transactions are showing up at https://explorer.bisq.network/testnet/. This seems like enough for now, i.e. no further changes necessary from @grazcoin's side. Here's a screenshot:

![image](https://user-images.githubusercontent.com/301810/32781099-058a004c-c944-11e7-8af9-758407e166bb.png)

**Comment by ManfredKarrer** [comment]
The old genesis tx is still marked as genesis tx and the new one as  normal tx. So it still needs a fix from @grazcoin

**Comment by cbeams** [comment]
Reclosing as dropped. We decided not to rebase every month, so the original testnet genesis tx is fine to stay the way it is for the remainder of Phase Zero.

See bisq-network/docs#2e566732808cde0c61fab7fd95be46ac79651162
